secrets:
  influxdb_admin_password:
    file: /home/mills/secrets/influxdb_admin_password
  influxdb_user:
    file: /home/mills/secrets/influxdb_user
  influxdb_password:
    file: /home/mills/secrets/influxdb_password
  mysql_root_password:
    file: /home/mills/secrets/mysql_root_password
  zabbix_db_password:
    file: /home/mills/secrets/zabbix_db_password
  zabbix_mysql_root_password:
    file: /home/mills/secrets/zabbix_mysql_root_password
  grafana_admin_password:
    file: /home/mills/secrets/gf_security_admin_password
  gf_security_admin_password:
    file: /home/mills/secrets/gf_security_admin_password
  grafana_password:
    file: /home/mills/secrets/grafana_password
  unifi_poller_password:
    file: /home/mills/secrets/up_unifi_password
  unifi_password:
    file: /home/mills/secrets/unifi_password
  up_influxdb_password:
    file: /home/mills/secrets/up_influxdb_password
  pihole_password:
    file: /home/mills/secrets/pihole_password
  snmp_password:
    file: /home/mills/secrets/snmp_password
  zabbix_web_pass:
    file: /home/mills/secrets/zabbix_web_pass
  grafana_admin_pass:
    file: /home/mills/secrets/grafana_admin_pass
  smb_password:
    file: /home/mills/secrets/smb_password
  smb_user:
    file: /home/mills/secrets/smb_user
  openvas_admin_password:
    file: /home/mills/secrets/openvas_admin_password
  wazuh_api_password:
    file: /home/mills/secrets/wazuh_api_password
  vault_root_token:
    file: /home/mills/secrets/vault_root_token
  trivy_db_password:
    file: /home/mills/secrets/trivy_db_password
  slack_webhook_url:
    file: /home/mills/secrets/slack_webhook_url
  slack_client_secret:
    file: /home/mills/secrets/slack_client_secret
  security_monitor_token:
    file: /home/mills/secrets/security_monitor_token
  threat_intel_api_key:
    file: /home/mills/secrets/threat_intel_api_key
  netdata_claim_token:
    file: /home/mills/secrets/netdata_claim_token
  healthchecks_secret_key:
    file: /home/mills/secrets/healthchecks_secret_key
  openai_api_key:
    file: /home/mills/secrets/openai_key
  openai_key:
    file: /home/mills/secrets/openai_key
  plex_auth_token:
    file: /home/mills/secrets/plex_auth_token
  plex_chimera_auth_token:
    file: /home/mills/secrets/plex_chimera_auth_token
  plex_token:
    file: /home/mills/secrets/plex_token
  github_client_secret:
    file: /home/mills/secrets/github_client_secret
  github_token:
    file: /home/mills/secrets/github_token
  unraid_api_key:
    file: /home/mills/secrets/unraid_api_key
  airflow_admin_password:
    file: /home/mills/secrets/airflow_admin_password
  matomo_db_password:
    file: /home/mills/secrets/matomo_db_password
  matomo_db_root_password:
    file: /home/mills/secrets/matomo_db_root_password
  my_secret:
    file: /home/mills/secrets/my_secret
  secret_name:
    file: /home/mills/secrets/secret_name
services:
  grafana-secure:
    image: grafana/grafana:latest
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
    secrets:
    - grafana_admin_password
  influxdb-secure:
    image: influxdb:1.8
    environment:
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD_FILE=/run/secrets/influxdb_admin_password
    secrets:
    - influxdb_admin_password
  unpoller-secure:
    image: ghcr.io/unpoller/unpoller:latest
    environment:
    - UP_UNIFI_DEFAULT_USER=unifipoll
    - UP_UNIFI_DEFAULT_PASS_FILE=/run/secrets/unifi_poller_password
    - UP_UNIFI_DEFAULT_URL=https://192.168.1.1
    - UP_INFLUXDB_URL=http://influxdb:8086
    - UP_INFLUXDB_USER=${INFLUXDB_ADMIN_USER:-admin}
    - UP_INFLUXDB_PASS_FILE=/run/secrets/influxdb_admin_password
    secrets:
    - unifi_poller_password
    - influxdb_admin_password
  influxdb:
    secrets:
    - influxdb_admin_password
  grafana:
    secrets:
    - grafana_admin_password
  unpoller:
    secrets:
    - unifi_poller_password
    - influxdb_admin_password
  pihole:
    secrets:
    - pihole_password
  pihole-secondary:
    secrets:
    - pihole_password
    profiles:
    - disabled
    ports: []
    restart: 'no'
  zabbix-mysql:
    environment: null
    secrets:
    - mysql_root_password
    - zabbix_db_password
  zabbix-server:
    secrets:
    - zabbix_db_password
  zabbix-web:
    secrets:
    - zabbix_db_password
  plex-data-collector:
    secrets:
    - plex_auth_token
    - plex_chimera_auth_token
    profiles:
    - disabled
    restart: 'no'
  slack-notifier:
    secrets:
    - slack_webhook_url
  swag:
    secrets:
    - slack_webhook_url
  mysql-exporter:
    secrets:
    - zabbix_db_password
    entrypoint:
    - /bin/sh
    - -c
    - 'printf "[client]

      user=zabbix

      password=$(cat /run/secrets/zabbix_db_password)

      " > /etc/mysql_exporter.cnf && exec /bin/mysqld_exporter --config.my-cnf=/etc/mysql_exporter.cnf'
  loki:
    user: 0:0
