#!/bin/bash
# Log Rotation Script for Maelstrom Infrastructure
# Generated by ultrathink analysis

set -e

LOG_DIR="/home/mills/logs"
RETENTION_DAYS=7

echo "[$(date)] Starting log rotation cleanup..."

# Rotate auto-recovery logs (keep 7 days)
find "$LOG_DIR" -name "auto-recovery-*.log" -mtime +$RETENTION_DAYS -delete 2>/dev/null || true

# Rotate health check logs (keep 14 days) 
find "$LOG_DIR" -name "health-check-*.log" -mtime +14 -delete 2>/dev/null || true

# Rotate orchestrator logs (keep 30 days)
find "$LOG_DIR" -name "orchestrator-*.log" -mtime +30 -delete 2>/dev/null || true

# Rotate Docker compose logs (keep 30 days)
find "$LOG_DIR" -name "docker-compose-*.log" -mtime +30 -delete 2>/dev/null || true

# Compress large active log files if they exceed 10MB
find "$LOG_DIR" -name "*.log" -size +10M -type f | while read -r logfile; do
    if [[ ! "$logfile" =~ .*\.gz$ ]]; then
        gzip "$logfile" && echo "Compressed: $logfile"
    fi
done

# Clean up empty log directories
find "$LOG_DIR" -type d -empty -delete 2>/dev/null || true

echo "[$(date)] Log rotation completed successfully"