name: Auth Smoke

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  auth-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Verify gh API noninteractive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          who=$(gh api /user --jq .login)
          echo "gh authenticated as: ${who}"
          gh api /rate_limit >/dev/null

      - name: Verify git to GitHub is noninteractive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          url="https://github.com/${GITHUB_REPOSITORY}.git"
          # Header injection with prompts disabled
          git -c http.extraheader="AUTHORIZATION: bearer ${GITHUB_TOKEN}" \
              -c core.askpass= -c credential.helper= \
              ls-remote "$url" | head -n1

      - name: Scan for banned interactive GitHub auth patterns
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/security/check_banned_github_auth.sh
