name: GitHub Probe

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  gh-probe:
    runs-on: ubuntu-latest
    steps:
      - name: noninteractive-check
        shell: bash
        run: |
          set -euo pipefail
          if [ -x /usr/local/bin/codex-preflight ]; then
            /usr/local/bin/codex-preflight
          else
            echo "codex-preflight not present on runner; skipping preflight."
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Probe GitHub connectivity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          make gh.auth
          make gh.probe

