name: Track CVE Drift (Key Images)

on:
  schedule:
    - cron: '0 6 * * 1'  # weekly on Monday 06:00 UTC
  workflow_dispatch:

jobs:
  drift-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install trivy and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y trivy jq
      - name: Scan pinned key images
        env:
          GRAFANA_TAG: ${{ vars.GRAFANA_TAG || '11.1.13-ubuntu' }}
          PROMETHEUS_TAG: ${{ vars.PROMETHEUS_TAG || 'v2.53.5' }}
          ALERTMANAGER_TAG: ${{ vars.ALERTMANAGER_TAG || 'v0.27.0' }}
          LOKI_TAG: ${{ vars.LOKI_TAG || '2.9.9' }}
          PROMTAIL_TAG: ${{ vars.PROMTAIL_TAG || '2.9.11' }}
          CADVISOR_TAG: ${{ vars.CADVISOR_TAG || 'v0.49.2' }}
        run: |
          bash scripts/security/scan_single_image.sh \
            grafana/grafana:${GRAFANA_TAG} \
            prom/prometheus:${PROMETHEUS_TAG} \
            prom/alertmanager:${ALERTMANAGER_TAG} \
            grafana/loki:${LOKI_TAG} \
            grafana/promtail:${PROMTAIL_TAG} \
            gcr.io/cadvisor/cadvisor:${CADVISOR_TAG}
      - name: Upload drift scan reports
        uses: actions/upload-artifact@v4
        with:
          name: cve-drift-reports
          path: reports/single_*.json
