name: Trivy Ignore Review Reminder

on:
  schedule:
    - cron: '0 12 * * *'  # daily at 12:00 UTC
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check review date and open issue if due
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'SECURITY.md';
            const body = fs.readFileSync(path, 'utf8');
            const m = body.match(/Review ignores by:\s*(\d{4}-\d{2}-\d{2})/);
            if (!m) { return core.info('No review date found.'); }
            const due = new Date(m[1]);
            const today = new Date();
            if (today > due) {
              const issueTitle = 'Review .trivyignore entries (past due)';
              const { data: issues } = await github.rest.search.issuesAndPullRequests({
                q: `repo:${context.repo.owner}/${context.repo.repo} is:issue in:title "${issueTitle}" state:open`
              });
              if (issues.total_count > 0) {
                core.info('Reminder issue already open.');
                return;
              }
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: 'Please review and prune .trivyignore entries as needed. Update SECURITY.md with a new review date.'
              });
            } else {
              core.info(`Review date not due yet: ${m[1]}`);
            }
